### ISSUE TITLE
Buttons cutting off text

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-themes/freedom#30]
On the Faceted Browse pages we still see dropdown menus too short for their contents:

<img width="1312" alt="Screenshot 2024-07-01 at 14 48 04" src="https://github.com/omeka-s-themes/freedom/assets/28012148/4e74fb63-c8b4-47da-8e25-af955bc7b414">
<img width="1316" alt="Screenshot 2024-07-01 at 14 48 10" src="https://github.com/omeka-s-themes/freedom/assets/28012148/eda73a37-b41a-4236-87ee-0b1ca2b4e9f7">

Whereas on normal browse you've made the dropdowns wider:

<img width="1320" alt="Screenshot 2024-07-01 at 14 50 18" src="https://github.com/omeka-s-themes/freedom/assets/28012148/9459144f-0ab4-4447-862b-245ae87eac7e">

I assume it's just calculating its width without taking the dropdown arrow width into account? Anyways, there's enough space on these pages usually that you can give them ample width.

**Comment by zerocrates** [comment]
It's an odd combination of the width styles set on those selects and their container... just having the selects have `width: auto` fixes this in the sense that they'll take up as much room as they need. Adding a min-width (could be zero or some actual reasonable minimum) to the selects and a `max-width: 100%` to the sorting form will make them shrink if they absolutely have to for page width, otherwise they'll wrap due to the flex-wrap on the outer container.

**Comment by nelsonamaya82** [comment]
Thanks @allanaaa @zerocrates, this is now fixed and will be included in the next release this week.
